[workspace]
members = [
  "collections/csv-table",
  "collections/document",
  "collections/pagination",
  "content/directory-listing",
  "content/imports",
  "content/includes",
  "content/table-of-contents",
  "syntax-highlight/external",
  "syntax-highlight/inline",
  "syntax-highlight/runtime",
]
