lang = "en"
host = "inline-syntax-highlight-example.uwe.app"

[page.meta]
description = "Syntax highlight with inline styles"
keywords = "Syntax, Highlight"

[dependencies."std::core"]
version = "^5"
apply = { styles = ["**"] }

[dependencies."std::blueprint::default"]
version = "^1"

[dependencies."std::syntax"]
version = "^1"

[syntax]
theme = "Solarized (light)"
