lang = "en"
host = "document-example.uwe.app"

[dependencies."std::core"]
version = "^5"
apply = { styles = ["**"] }

[dependencies."std::blueprint::default"]
version = "^1"

[page.meta]
description = "HTML/CSS Color Names"
keywords = "Colors, Markup, CSS, Collections"

[db.load.colors]
provider = "document"
type = "json"
from = "collections/colors/names.json"

[db.load.colors.on.all]
key = "*"

[pages."index.md".query]
name = "colors"
index = "all"
include-docs = true
