lang = "en"
host = "entities-example.uwe.app"

[dependencies."std::core"]
version = "^4"
apply = { styles = ["**"] }

[dependencies."std::paginate"]
version = "^1"
apply = { styles = ["**"] }

[dependencies."std::blueprint::default"]
version = "^1"

[page.meta]
description = "HTML Entity List"
keywords = "HTML, Entity, Collections"

[db.load.entity]
provider = "document"
type = "json"
from = "collections/entity/names.json"

[db.load.entity.on.all]
key = "*"

[pages."index.md".query]
name = "entity"
index = "all"
include-docs = true
page = { size = 100 }

[redirects]
"/" = "/1/"
