lang = "en"
host = "localhost"
[dependencies."std::core"]
version = "~4.1.6"

[dependencies."std::core".apply]
styles = ["**"]

[dependencies."std::blueprint::default"]
version = "1.0.0"
[page.meta]
description = "Website"
keywords = "Vanilla, Website"
