lang = "en"
host = "alerts-example.uwe.app"

[page.meta]
description = "Alerts"
keywords = "Alerts, Info, Tips, Warn, Error"

[dependencies."std::core"]
version = "^5"
apply = { styles = ["**"] }

[dependencies."std::blueprint::default"]
version = "^1"

[dependencies."std::alert"]
version = "^1"
apply = { styles = ["**"] }

[dependencies."std::syntax"]
version = "^1"

[syntax]
theme = "Solarized (light)"
