lang = "en"
host = "crumbtrails-example.uwe.app"

[page.meta]
description = "Crumbtrails Navigation"
keywords = "Crumbtrails, Navigation"

[dependencies."std::core"]
version = "^4"
apply = { styles = ["**"] }

[dependencies."std::blueprint::default"]
version = "^1"

[dependencies."std::crumbtrail"]
version = "^1"
apply = { styles = ["**"] }
path = "../../../plugins/std/crumbtrail"

[dependencies."std::syntax"]
version = "^1"

[syntax]
theme = "Solarized (light)"
