lang = "en"
host = "external-syntax-highlight-example.uwe.app"

[dependencies."std::core"]
version = "^4"
apply = { styles = ["**"] }

[dependencies."std::blueprint::default"]
version = "^1"

[dependencies."std::syntax"]
version = "^1"
apply = { styles = [ { to = "**", filter = "solarized-light.css" } ] }

[page.meta]
description = "Syntax highlight with an external stylesheet"
keywords = "Syntax, Highlight"

# Must define the `[syntax]` table to activate the highlighting
[syntax]
